# tests/conftest.py
import pytest
from pathlib import Path
import json
import os

@pytest.fixture
def valid_environment(tmp_path):
    """
    Sets up a valid temporary environment for testing CLI commands.
    Creates dummy data files, manifest files, and returns a dictionary
    of environment variables that tests can pass to `CliRunner.invoke`.
    """
    # Create sample data file
    data_path = tmp_path / "data.csv"
    data_path.write_text("feature1,feature2\n1.0,2.0\n1.1,2.1\n0.9,1.9\nanomaly_trigger,0.0") # Added more varied data

    # Create valid data manifest (points to the data.csv above)
    # The hash should ideally be correct for the content of data.csv
    # For "feature1,feature2\n1.0,2.0\n1.1,2.1\n0.9,1.9\nanomaly_trigger,0.0"
    # sha256 is approx "f2..." - let's use a placeholder as tests mock verify_data_integrity
    manifest_content = {
        "data_input": {
            "path": str(data_path),
            "hash_sha256": "sha256_hash_placeholder_for_data_csv"
        }
    }
    data_manifest_path = tmp_path / "data_manifest.json" # Specific name for clarity
    data_manifest_path.write_text(json.dumps(manifest_content))

    # Create sovereign code manifest (for scripts.verify_integrity)
    # This manifest would normally be generated by `scripts/verify_integrity.py generate`
    # For testing verify_code_integrity, it's often mocked, but if not, it needs to exist.
    # Let's assume it's mocked in the tests that focus on data verification.
    # If a test needs a real one, that test or fixture should create it.
    # For now, the `verify_code_integrity` in `src/main.py` refers to `scripts.verify_integrity.main`
    # which implies it might try to read "sovereign_manifest.json" from project root.
    # The user's test suite mocks this, so a dummy one here might not be strictly needed for *those* tests.
    # However, if `scripts.verify_integrity.main()` is called without args, it defaults to current dir.
    # For robustness, let's create a dummy one in tmp_path if needed.
    # The user's conftest.py named it SOVEREIGN_MANIFEST_PATH.

    sovereign_manifest_file_path = tmp_path / "sovereign_manifest.json" # Default name used by script
    sovereign_manifest_content = {
        "algorithm": "sha256",
        "files": {
            # Add some dummy entries to make it look like a real manifest
            "src/main.py": "dummy_hash_for_main_py_in_conftest",
            "src/config.py": "dummy_hash_for_config_py_in_conftest"
        }
    }
    sovereign_manifest_file_path.write_text(json.dumps(sovereign_manifest_content))

    # Define environment variables to be passed to CliRunner.invoke(env=...)
    # These will be picked up by `settings = Settings()` in the CLI command.
    env_config = {
        "INPUT_DATA_PATH": str(data_path),
        "DATA_MANIFEST_PATH": str(data_manifest_path), # Specific data manifest to check
        # SOVEREIGN_MANIFEST_PATH is not directly used by settings, but by verify_integrity.py script
        # if it were to load from a non-default path. Our script uses default "sovereign_manifest.json"
        # in its execution CWD. When CLI calls it, CWD might be project root or /app.
        # The tests mock `verify_code_integrity`, so this path isn't strictly used by those mocks.
        # Let's assume the test mocks handle the code verification part.
        "MANIFEST_OUTPUT_PATH": str(tmp_path / "training_manifests"), # For train command if it runs
        "MODEL_OUTPUT_PATH": str(tmp_path / "model.joblib") # For train command if it runs
    }

    # Ensure directories that might be written to by commands exist
    Path(env_config["MANIFEST_OUTPUT_PATH"]).mkdir(parents=True, exist_ok=True)
    Path(env_config["MODEL_OUTPUT_PATH"]).parent.mkdir(parents=True, exist_ok=True)

    return env_config
